spring.application.name=backend
spring.data.mongodb.uri=mongodb+srv://piyushharad471_db_user:Jidnyasa2005@cluster0.0jfmf1r.mongodb.net/expenseDB?retryWrites=true&w=majority
#spring.data.mongodb.database=expenseDB

spring.data.mongodb.database=expenseDB
server.port=8080

